#!/bin/sh

# .husky/post-checkout
current_branch=$(git rev-parse --abbrev-ref HEAD)
previou_branch=$(git rev-parse --abbrev-ref @{-1})

send_email() {
  local smtp_server="smtps://smtp.gmail.com:465"
  local from_email="youremail"
  local user_acc="youremail"
  local user_pass=""
  local to_email="youremail"
  local subject="Thông tin lỗi khi checkout branch ngày: $(date)"
  local body="$1"

  echo -e "From: $from_email\nTo: $to_email\nSubject: $subject\n\n$body" | \
  curl --url "$smtp_server" --ssl-reqd \
    --mail-from "$from_email" \
    --mail-rcpt "$to_email" \
    --user "$user_acc:$user_pass" \
    -T -
}

color_text() {
  if [ "$1" == "red" ]; then
    echo -e "\e[1;31m$2\e[0m"
  elif [ "$1" == "green" ]; then
    echo -e "\e[1;32m$2\e[0m"
  elif [ "$1" == "yellow" ]; then
    echo -e "\e[1;33m$2\e[0m"
  elif [ "$1" == "blue" ]; then
    echo -e "\e[1;34m$2\e[0m"
  elif [ "$1" == "purple" ]; then
    echo -e "\e[1;35m$2\e[0m"
  elif [ "$1" == "cyan" ]; then
    echo -e "\e[1;36m$2\e[0m"
  else
    echo "$2";
  fi
}

if [ "$current_branch" != "dev" ]; then
  if [ "$previou_branch" == "master" ]; then
    BODY=""
    BODY+="Previous branch: [$previou_branch]"
    BODY+="\n"
    BODY+="Current branch: [$current_branch]"
    BODY+="\n"
    BODY+="Log time: $(date)"
    BODY+="\n"
    BODY+="Git user name: $(git config user.name)"
    BODY+="\n"
    BODY+="Git user email: $(git config user.email)"
    BODY+="\n"
    BODY+="****************************************************************************************"
    echo "$BODY" >>.husky/post-checkout.log
    send_email "$BODY"

    prevText=$(color_text "yellow" "$previou_branch")
    currentText=$(color_text "yellow" "$current_branch")
    attentionText=$(color_text "yellow" "LƯU Ý!!!")
    moreText=$(color_text "red" "Bạn vừa checkout từ:")
    echo "$attentionText $moreText $prevText ---> $currentText."
  fi
fi